### ISSUE TITLE
安卓没有执行onPushingState的回调，但是能正常触发网络请求

### ISSUE THREAD

**Issue by Mr-nan** [hzl123456/react-native-rk-pull-to-refresh#13]

**Comment by hzl123456** [comment]
1.2.5版本已修改，demo也同步修改

**Comment by xusirfm** [comment]
还有就是 android 上不能执行 startRefresh()

**Comment by hzl123456** [comment]
1.2.6版本已修复

**Comment by hzl123456** [comment]
如果不起效果的话，，，第一次调用可以延迟调用（之后就没关系了），，，类似
setTimeout(() => this.refresh && this.refresh.startRefresh(), 100)
