### ISSUE TITLE
安卓初始状态出现以下问题

### ISSUE THREAD

**Issue by congtaoa** [hzl123456/react-native-rk-pull-to-refresh#15]
"react-native": "0.59.2",
 "react-native-rk-pull-to-refresh": "^1.2.7",

  
![image](https://user-images.githubusercontent.com/18671378/55709449-e76f6e80-5a1a-11e9-96bb-ec6b7e8df4d6.png)
请求解答！！

**Comment by Grom-S** [comment]
@Congtaoa have you figured out the solution? I am having the same problem

**Comment by rafalzawadzki** [comment]
Same problem here, I only know that `style={{flex: 1}}` has some influence in this, but overall figuring out how to make this library work was a failed attempt

**Comment by congtaoa** [comment]
@Grom-S  not yet

**Comment by fish-jade** [comment]
Pullable.android.js中删除所有的flex:1,并将getScrollable用view包裹起来 <View>{this.getScrollable()}</View>

**Comment by congtaoa** [comment]
@WZWGemini  谢谢！已解决

**Comment by zcmain** [comment]
I encountered the same problem and tried to solve it by adding onFinishInflate() to the onMeasure ()  in PtrFrameLayout
