### ISSUE TITLE
下拉后不松手，onPullStateChangeHeight 回调多次且状态混乱，无法使用

### ISSUE THREAD

**Issue by jinzunyue** [hzl123456/react-native-rk-pull-to-refresh#5]
IOS 上操作：
1. 使劲向下拉
2. 向下拉后，不松手，来回上下拉

现象：
onPullStateChangeHeight 回调多次，并且 pullState 的值混乱

结论：会导致刷新的网络请求多次请求，多次完成，最终界面闪烁。无法使用。

**Comment by hzl123456** [comment]
下拉刷新的回调是onPullRelease方法，这个只在手指离开屏幕的时候根据下拉的距离才会去进行回调，，
而onPullStateChangeHeight的回调是下拉距离的变化才会回调，主要目的是根据下拉的距离做出不同的样式调整，
pullState的值是根据下拉的距离进行设置的，小于头部高度的时候是“pulling”，大于的时候是“pullok”，只有在手指释放并且是“pullok”状态下才会变成“pullrelease”状态，同时进行onPullRelease回调
所以按照你上面的操作的话是不会进行多次的下拉刷新回调的

**Comment by jinzunyue** [comment]
恩，之前确实是我用错了,所以我自己关闭了。
