### ISSUE TITLE
iOS 端一个偶发 bug,,,,一个设计缺陷

### ISSUE THREAD

**Issue by jinzunyue** [hzl123456/react-native-rk-pull-to-refresh#7]
iOS 偶发bug: 
配合 ScrollableTabView 使用，多次快速下拉刷新，很容易出现下拉时还能左右滑动的现象。打印 log 发现都是正常的，还请看一下。
设计缺陷：
先向上稍微滑动一点，然后在向下滑动，不能触发下拉刷新动作。

**Comment by jinzunyue** [comment]
即使是你的 Demo 也会有这样的现象。
1. 运行 Demo
2. 点击 ScrollView 标签
3. 点击 View 标签
4. 多次下拉刷新 View 标签，下拉时，同时向左偏。偶发下拉时能左右滑动，且滑动结束，右边的界面会侵占左侧的界面。

**Comment by jinzunyue** [comment]
关闭是点错了。
即使是你的 Demo 也会有这样的下拉刷新的问题。
1. 运行 Demo
2. 点击 ScrollView 标签
3. 点击 View 标签
4. 多次下拉刷新 View 标签，下拉时，同时向左偏。偶发下拉时能左右滑动，且滑动结束，右边的界面会侵占左侧的界面。
手机截图：https://pan.baidu.com/s/182lfmoGPcnm3ucWkzdbHGA

**Comment by hzl123456** [comment]
目前ios的下拉刷新采用的是RN的控件进行组合使用的，通过setState()的值去改变是否可以左右滑动，这个是有一定的延迟性的，那个控件距离顶部的距离也是从RN内部的控件的属性值获取的。。。。。。可能这些也是RN的局限的地方吧，，，，如果需要比较好的效果的话可能就得原生封装了，，，目前我自己的项目中android和ios都是原生封装的

**Comment by jinzunyue** [comment]
好吧。。
